version: "3.2"
services:
  hrabbitmq:
    image: rabbitmq:latest
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/data:/var/lib/rabbitmq/
        - ~/logs:/var/log/rabbitmq
    networks:
        - mynet

  hproducer:
    image: rmq-producer:latest
    container_name: 'producer'
    ports:
      - 8080:8080
    depends_on:
      - hrabbitmq
    networks:
      - mynet

  hconsumer:
    image: rmq-consumer:latest
    container_name: 'consumer'
    depends_on:
      - hrabbitmq
    networks:
      - mynet

networks:
  mynet:
